### ISSUE TITLE
Premades being used instead of recipe?

### ISSUE THREAD

**Issue by rushtothesun** [Lailloken/Lailloken-UI#15] opened 2022-02-21 05:57 UTC
I have Treant horde in my inventory and I have the Treant horde recipe ready in my inventory ( Toxic, Sentinel, Steel Infused).

When I click scan i see Ready: Treant Horde

But when I click Treant Horde it's selecting the already made Treant horde instead of the recipe. 
It does this with other things too.

**Comment by Lailloken** [comment] 2022-02-21 08:28
Treant Horde is not on your priority list, right? Because then this behavior would be a bug. What you are describing is the current intended behavior of the burn pile: the highest-tier non-prioritized mods get burned first. I could change it to work the other way around -- you are the first to mention this.

**Comment by rushtothesun** [comment] 2022-02-21 16:15
I don't have anything prioritized. The burn pile only shows up when something is prioritized. Also could the Ready/Burn window be restored when you open the Archnemesis tab instead of scanning each time? If i get interrupted while in the Archnemesis window I have to scan again or if I leave the map when I have part of a recipe in the altar and then come back I have to scan again but the recipe won't show because some of the components are already in the altar.

**Comment by Lailloken** [comment] 2022-02-21 17:21
> I don't have anything prioritized. The burn pile only shows up when something is prioritized. Also could the Ready/Burn window be restored when you open the Archnemesis tab instead of scanning each time? If i get interrupted while in the Archnemesis window I have to scan again or if I leave the map when I have part of a recipe in the altar and then come back I have to scan again but the recipe won't show because some of the components are already in the altar.

Closing the ready window was originally intended to prevent the tool and your inventory from going out of sync in case the user just ran encounters non-stop without re-scanning. I didn't consider leaving the map because I play SSF -- that's a very good point. I guess I'll just make it the user's responsibility to re-scan frequently. Thanks for the feedback.

**Closed** 2022-02-22 17:23 UTC
