### ISSUE TITLE
Item-Info: Highlight Class Specific

### ISSUE THREAD

**Issue by peterm2024** [Lailloken/Lailloken-UI#433] opened 2024-07-30 21:05 UTC
Hey,

it seems that Highlight Class Specific stopped working for me in version 1.53.3. The latest version I can use it is 1.53.2.
I'm using it for tiering the usefulness of the item, meaning cyan is must have and green is nice to have.
The most items where configured before 1.53.2 so there was no need to change it - the cyan box still works. Now I need a new affix and long clicked an item but nothing happened (1.54.5).

Thanks Peter

**Comment by Lailloken** [comment] 2024-07-31 06:02
Thanks for reporting, I'll look into it asap.

> Now I need a new affix and long clicked an item but nothing happened (1.54.5).

Affixes are not tied to any databases within the tool, they're simply copied from the game. So you can still use the old version that works for the time being.

**Comment by Lailloken** [comment] 2024-08-02 14:05
The issue was caused by an oversight and it's now fixed in [v1.54.6](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.54.6).

**Closed** 2024-08-05 14:59 UTC
