### ISSUE TITLE
Can't take screenshots for Betrayal

### ISSUE THREAD

**Issue by nobewayo** [Lailloken/Lailloken-UI#472] opened 2024-09-11 19:10 UTC
As soon as I mark what to screenshot, i briefly see the drop down to choose what it is, but not even a second later it closes at it says:
"Screencap aborted."

Again, using GeForce Now. Don't know if that's the issue..

**Comment by Lailloken** [comment] 2024-09-11 20:22
Yeah, it's GeForce Now. I had to implement a workaround because of how GFN handles clicks. Basically, the tool automatically switches focus to whichever window the cursor is hovering over. The issue is that the Betrayal setup automatically closes as soon as it's no longer focused.

I'll fix it for the next release, sorry about that. I use a separate account to test GFN things, and it's only in act 1, so it's likely I have missed stuff here or there.

**Comment by nobewayo** [comment] 2024-09-12 19:29
No worries, I'll keep reporting issues that I find.

**Comment by Lailloken** [comment] 2024-09-15 13:12
Should be fixed in [v1.55.4](https://github.com/Lailloken/Lailloken-UI/releases/tag/v1.55.4)

**Closed** 2024-09-26 11:00 UTC
